### ISSUE TITLE
The Promise returned by this middleware never get resolved

### ISSUE THREAD

**Issue by vincent-yao27** [vagusX/koa-proxies#13]
It bothered me a lot that I found that the callback of `proxy.web` in http-proxy is invoked only when errors occurred. The method is not a sync function and has no callbacks that are guaranteed to be triggered. That's an insane feature (or bug), which made me sought and tried a lot of ways to solve it. But it was in vain.
Then I saw your code returning a Promise without taking any measure to deal with that "feature". I was wondering if I was wrong? It was just so simple? So I tested your code once and once again. Finally, I drew a conclusion that the Promise didn't get resolved at all.

**Comment by iwestlin** [comment]
是啊，为啥要返回一个promise，为啥只在出错的时候resolve它， @vagusX 能给解释下吗。。

目测大家都是中国人我就用中文问了……

**Comment by vagusX** [comment]
According to https://github.com/nodejitsu/node-http-proxy/issues/951#issuecomment-179904134, the third argument in `proxy.web` is a callback but invoking when meeting a error.

**Comment by iwestlin** [comment]
@vagusX I think you are missing the point...
@vincent-yao27 and I are wondering why this middleware returns a promise which might be unfulfilled forever, and that may cause memory leaks. For example:

```javascript
const proxy = require('koa-proxies')
const error_handler = async function (ctx, next) {
  try {
    await next()
  } catch (e) {
    // report error
  }
}

app.use(error_handler)
app.use(proxy({...}))
```
when program runs into `await next()`, it will get stuck, because the promise returned by proxy never resolve or reject……

I think this might fix it: https://github.com/catamphetamine/webapp/blob/80f2c37596e878895eaa129dc7666133e472443f/code/common/web%20server.js#L747-L766

**Comment by vagusX** [comment]
Oh I see, I will fix it as soon as possible

**Comment by vagusX** [comment]
revert it back to https://github.com/vagusX/koa-proxies/pull/27
